global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'discovery-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8761']
  - job_name: 'api-gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']
  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
        - targets: [ 'localhost:8082']
  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
        - targets: [ 'localhost:8083']
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
        - targets: [ 'localhost:8084']
